const TOKEN_VERIFY_ERROR="TOKEN_VERIFY_ERROR";
const Account_IS_NOT_EXIST = "Account_IS_NOT_EXIST";
const PASSWORD_IS_NOT_SAME="PASSWORD_IS_NOT_SAME";
module.exports = {
    TOKEN_VERIFY_ERROR,
    Account_IS_NOT_EXIST,
    PASSWORD_IS_NOT_SAME
}